In [1]:
import pandas as pd

In [21]:
prism1 = pd.read_csv('../../data/primary-screen-replicate-collapsed-logfold-change.csv').rename(columns={'Unnamed: 0': 'depmap_id'})
prism2 = pd.read_csv('../../data/secondary-screen-replicate-collapsed-logfold-change.csv').rename(columns={'Unnamed: 0': 'depmap_id'})
prism = prism1.merge(prism2, on='depmap_id', how='outer')
prism.head()

,depmap_id,BRD-A00077618-236-07-6::2.5::HTS,BRD-A00100033-001-08-9::2.5::HTS,BRD-A00147595-001-01-5::2.5::HTS,BRD-A00218260-001-03-4::2.5::HTS,BRD-A00376169-001-01-6::2.5::HTS,BRD-A00520476-001-07-4::2.5::HTS,BRD-A00546892-001-02-6::2.5::HTS,BRD-A00578795-001-04-3::2.5::HTS,BRD-A00758722-001-04-9::2.5::HTS,...,BRD-U25960968-000-01-9::10::HTS002,BRD-U25960968-000-01-9::2.5::HTS002,BRD-U45393375-000-01-6::0.000610351569230769::HTS002,BRD-U45393375-000-01-6::0.00244140624615385::HTS002,BRD-U45393375-000-01-6::0.009765625::HTS002,BRD-U45393375-000-01-6::0.0390625::HTS002,BRD-U45393375-000-01-6::0.15625::HTS002,BRD-U45393375-000-01-6::0.625::HTS002,BRD-U45393375-000-01-6::10::HTS002,BRD-U45393375-000-01-6::2.5::HTS002
0,ACH-000001,-0.015577,-0.449332,0.489379,0.206675,0.272730,0.021036,-0.025460,0.467158,-0.736306,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,ACH-000007,-0.095730,0.257943,0.772349,-0.438502,-0.732832,0.779201,0.426523,-1.288508,-0.476133,...,-1.211172,-0.030709,0.109745,1.091437,0.845174,0.914664,0.308181,0.487404,0.100248,1.018868
2,ACH-000008,0.379480,-0.596132,0.548056,0.422269,-0.216986,0.081866,0.145335,-0.570841,-0.512119,...,0.002228,0.764709,0.195910,0.440849,0.130811,0.114002,0.227759,0.230646,-0.148456,0.110857
3,ACH-000010_FAILED_STR,0.118890,-0.231615,0.621937,-0.202707,-1.005139,-0.213739,0.020246,-0.795278,NaN,...,NaN,NaN,-0.445411,0.403367,-0.428090,-0.050511,1.262123,0.677607,0.144283,-0.090171
4,ACH-000011,0.145346,-0.499274,0.267470,0.157804,-0.272286,0.207768,0.004464,-0.191680,-0.310375,...,0.371009,-0.496587,0.317756,0.422177,0.298953,0.322027,0.149719,0.328480,0.355459,0.113343

In [23]:
# need to map depmap id to cell iname 
info1 = pd.read_csv('../../data/DepMap-2019q1-celllines_v2.csv')[['DepMap_ID', 'CCLE_Name']].rename(columns={'DepMap_ID': 'depmap_id', 'CCLE_Name': 'ccle_name'})
info2 = pd.read_csv('../../data/cellinfo_beta.txt', sep='\t')[['ccle_name', 'cell_iname']]
info = pd.merge(info1, info2, on='ccle_name', how='inner')[['depmap_id', 'cell_iname']]
info.to_csv('../extdata/depmap2iname.csv', index=False)
info.head()

    depmap_id cell_iname
0  ACH-000002       HL60
1  ACH-000012     HCC827
2  ACH-000017      SKBR3
3  ACH-000019       MCF7
4  ACH-000052       A673

In [24]:
prism = prism.merge(info, on='depmap_id', how='inner')
prism.head()

,depmap_id,BRD-A00077618-236-07-6::2.5::HTS,BRD-A00100033-001-08-9::2.5::HTS,BRD-A00147595-001-01-5::2.5::HTS,BRD-A00218260-001-03-4::2.5::HTS,BRD-A00376169-001-01-6::2.5::HTS,BRD-A00520476-001-07-4::2.5::HTS,BRD-A00546892-001-02-6::2.5::HTS,BRD-A00578795-001-04-3::2.5::HTS,BRD-A00758722-001-04-9::2.5::HTS,...,BRD-U25960968-000-01-9::2.5::HTS002,BRD-U45393375-000-01-6::0.000610351569230769::HTS002,BRD-U45393375-000-01-6::0.00244140624615385::HTS002,BRD-U45393375-000-01-6::0.009765625::HTS002,BRD-U45393375-000-01-6::0.0390625::HTS002,BRD-U45393375-000-01-6::0.15625::HTS002,BRD-U45393375-000-01-6::0.625::HTS002,BRD-U45393375-000-01-6::10::HTS002,BRD-U45393375-000-01-6::2.5::HTS002,cell_iname
0,ACH-000012,0.103348,0.063870,0.088670,0.484581,-0.007589,0.227250,0.002759,-0.694161,NaN,...,0.325123,0.416630,0.539603,-0.239022,0.097228,0.216950,-0.002360,-0.060300,0.004053,HCC827
1,ACH-000019,-0.025927,-0.021953,0.018010,0.052074,-0.155201,0.001383,-0.304017,-0.498156,-1.707478,...,0.611339,0.485832,0.161235,0.291401,0.087299,0.469056,0.364959,-0.079961,0.295213,MCF7
2,ACH-000048,-0.901099,-1.088498,0.461293,-0.043921,-0.387045,0.155468,0.114820,-0.484273,-1.015321,...,NaN,0.219759,0.360329,0.418320,-0.110880,0.129576,0.041631,0.441861,-0.133081,TOV112D
3,ACH-000052,-0.133103,-0.853926,0.518615,0.471141,-0.357434,0.347287,0.196238,0.279413,-0.539456,...,0.148239,0.426911,0.325985,0.103001,0.127355,0.106277,0.686774,0.525562,0.360317,A673
4,ACH-000087,-0.445527,0.047369,0.781814,-0.042403,-0.210302,0.915749,-0.190122,-0.832334,-0.413608,...,NaN,0.213599,0.486850,0.336409,0.424195,-0.304525,-0.427521,0.001789,-0.103303,SKES1

In [33]:
prism = prism.set_index('cell_iname').drop(columns=['depmap_id']).stack().reset_index().rename(columns={'level_1': 'column_name', 0: 'logfold_change'})
prism.head()

  cell_iname                       column_name  logfold_change
0     HCC827  BRD-A00077618-236-07-6::2.5::HTS        0.103348
1     HCC827  BRD-A00100033-001-08-9::2.5::HTS        0.063870
2     HCC827  BRD-A00147595-001-01-5::2.5::HTS        0.088670
3     HCC827  BRD-A00218260-001-03-4::2.5::HTS        0.484581
4     HCC827  BRD-A00376169-001-01-6::2.5::HTS       -0.007589

In [35]:
meta1 = pd.read_csv('../../data/primary-screen-replicate-collapsed-treatment-info.csv')
meta2 = pd.read_csv('../../data/secondary-screen-replicate-collapsed-treatment-info.csv')
meta = pd.concat([meta1, meta2], axis=0)
meta = meta.assign(pert_id = [x.split('-00')[0] for x in meta['broad_id']])
meta = meta[['column_name', 'pert_id', 'name', 'dose', 'screen_id']]

prism = prism.merge(meta, on='column_name', how='inner') 
prism.head()

,cell_iname,column_name,logfold_change,pert_id,name,dose,screen_id
0,HCC827,BRD-A00077618-236-07-6::2.5::HTS,0.103348,BRD-A00077618-236-07-6,8-bromo-cGMP,2.5,HTS
1,HCC827,BRD-A00100033-001-08-9::2.5::HTS,0.063870,BRD-A00100033,nifurtimox,2.5,HTS
2,HCC827,BRD-A00147595-001-01-5::2.5::HTS,0.088670,BRD-A00147595,balaglitazone,2.5,HTS
3,HCC827,BRD-A00218260-001-03-4::2.5::HTS,0.484581,BRD-A00218260,flutrimazole,2.5,HTS
4,HCC827,BRD-A00376169-001-01-6::2.5::HTS,-0.007589,BRD-A00376169,KBG,2.5,HTS

In [36]:
prism.shape

(1519396, 7)